import pymysql
import os
import sys

# Ensure we can import from utils
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

try:
    from utils.sql_config import DATABASES
except ImportError:
    # Fallback if running from a different location or path issues
    sys.path.append(os.path.join(current_dir, '..'))
    from utils.sql_config import DATABASES

def extract_schema():
    # Target the agent_db (host ending in 13)
    db_key = 'agent_db'
    if db_key not in DATABASES:
        print(f"Error: {db_key} not found in configuration.")
        return

    config = DATABASES[db_key]
    
    print(f"Connecting to database '{config['database']}' at {config['host']}...")
    
    try:
        conn = pymysql.connect(
            host=config['host'],
            user=config['username'],
            password=config['password'],
            database=config['database'],
            port=config['port'],
            charset='utf8mb4'
        )
    except Exception as e:
        print(f"Failed to connect: {e}")
        return
    
    output_file = os.path.join(current_dir, 'agent_db_schema.sql')
    
    try:
        with conn.cursor() as cursor:
            # Get tables
            cursor.execute("SHOW TABLES")
            tables = cursor.fetchall()
            
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(f"-- Schema dump for database: {config['database']}\n")
                f.write(f"-- Host: {config['host']}\n")
                f.write(f"-- Generated by extract_schema.py\n")
                f.write("-- \n\n")
                f.write("SET NAMES utf8mb4;\n")
                f.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")
                
                for table in tables:
                    # fetchall returns tuples, e.g. (table_name,)
                    table_name = table[0]
                    print(f"Extracting table: {table_name}")
                    
                    try:
                        cursor.execute(f"SHOW CREATE TABLE `{table_name}`")
                        # fetchone returns (table_name, create_statement)
                        create_statement = cursor.fetchone()[1]
                        
                        f.write(f"-- Table structure for table `{table_name}`\n")
                        f.write(f"DROP TABLE IF EXISTS `{table_name}`;\n")
                        f.write(f"{create_statement};\n\n")
                    except Exception as e:
                        print(f"Error extracting table {table_name}: {e}")
                        f.write(f"-- Error extracting table {table_name}: {e}\n\n")

                f.write("SET FOREIGN_KEY_CHECKS = 1;\n")
                    
        print(f"Success! Schema saved to: {output_file}")
        
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    extract_schema()
